# Generated by Django 4.0.6 on 2022-08-28 17:01

import Application.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(default='', max_length=100)),
                ('holder', models.CharField(default='', max_length=100)),
                ('task', Application.fields.TaskField(choices=[('1', 'task 1'), ('2', 'task 2'), ('3', 'task 3')], max_length=1)),
                ('day', models.DateField()),
                ('time', Application.fields.TimeField(choices=[('1', '12:00 - 14:00'), ('2', '14:00 - 16:00'), ('3', '16:00 - 18:00')], max_length=1)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telegram_id', models.IntegerField(default=0)),
                ('is_teacher', models.BooleanField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
