# Generated by Django 4.0.6 on 2022-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingsystem',
            name='user',
            field=models.TextField(),
        ),
    ]
